name: ar_natomy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.9.1
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/human_heart.glb
    - assets/models/skeleton.glb
    - assets/models/muscle_anatomy.glb
    - assets/models/lymphatic_system_overview.glb
    - assets/models/skeleton.glb
    - assets/web/model_viewer_with_hotspots.html
