name: arnatomy
description: "An augmented reality application for interactive 3D anatomy visualization and learning."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.9.1
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/human_heart.glb
    - assets/models/skeletal_system.glb
    - assets/models/muscular_system.glb
    - assets/models/lymphatic_system.glb

    - assets/heart_hotspots.html
    - assets/heart_styles.css
    - assets/heart_interactions.js
